# Generated by Django 5.2 on 2025-04-30 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_owner_created_at_owner_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique code for the species (e.g., CANINE, FELINE)', max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Species',
            },
        ),
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the breed', max_length=100)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breeds', to='main.species')),
            ],
            options={
                'ordering': ['species__code', 'name'],
                'unique_together': {('species', 'name')},
            },
        ),
    ]
