# Generated by Django 5.2 on 2025-05-01 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
