# Generated by Django 5.2 on 2025-05-01 18:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_squashed_0006_alter_owner_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_date', models.DateField(default=django.utils.timezone.now, help_text='Date of the visit/case.')),
                ('complaint', models.TextField(blank=True, help_text='Primary reason for the visit/consultation.')),
                ('history', models.TextField(blank=True, help_text='Relevant medical history for this case.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='main.owner')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='main.patient')),
            ],
            options={
                'ordering': ['-case_date', '-updated_at'],
            },
        ),
    ]
